### ISSUE TITLE
Remove stale text from page

### ISSUE THREAD

**Issue by manishprivet** [manishprivet/electify#2]
![image](https://user-images.githubusercontent.com/54291836/94888008-62410a80-0495-11eb-81c8-80a6fd4f5ad5.png)

At https://electify.manish.codes/create, there's this stale text that needs to be removed.

**Comment by sonuishaq67** [comment]
Ill take this up!

**Comment by manishprivet** [comment]
@sonuishaq67 Assigned it to you

**Comment by sonuishaq67** [comment]
Ive sent a pr #4

**Comment by manishprivet** [comment]
Thanks :)
