### ISSUE TITLE
Add title and meta tags for each page and layout

### ISSUE THREAD

**Issue by manishprivet** [manishprivet/electify#3]
Right now, apart from the homepage, the `<title>` tag is nowhere present on the website.
Add them to each and every page... You can see an example of how it's done in `pages/index.tsx`

![image](https://user-images.githubusercontent.com/54291836/94888337-63266c00-0496-11eb-99bf-93a7f6eb38f8.png)

Also, apart from the title, many tags like description and such are common for each page, which are present in `pages/_document.tsx`... Move the `<link rel='icon'...` from `index.tsx` to there

**Comment by wilsantow** [comment]
@manishprivet can I work on this issue?

**Comment by manishprivet** [comment]
@wilsantow Sure
