### ISSUE TITLE
Fix footer link to correct one

### ISSUE THREAD

**Issue by manishprivet** [manishprivet/electify#8]
Right now, the link on the footer links to `manishprivet.github.io` which is a dead link.

![image](https://user-images.githubusercontent.com/54291836/94920476-05187980-04d4-11eb-86b9-cb631c85f69b.png)

Change it to `https://manish.codes`

**Comment by sejaljain123** [comment]
I want to work on this project

**Comment by manishprivet** [comment]
Assigned to you @sejaljain123 :)
